#!/usr/bin/env python

import argparse
import os
import re
import sys

_verbose = False


def log(s):
  print(s)


def loge(s):
  sys.stderr.write(s + "\n")
  sys.stderr.flush()


def logv(s):
  if _verbose:
    log(s)


def abort(s):
  loge(s)
  sys.exit(1)


class FreeMode(object):
  def __init__(self, gen):
    self.gen = gen

  def consume(self, line, no):
    if not line.strip().startswith("/*!"):
      return self
    else:
      cmd = line.strip()[3:]
      depth = line.find("/*!")
      if cmd == "md":
        return MarkdownMode(self.gen, depth)
      elif cmd.startswith("begin-code"):
        return CodeMode(self.gen, depth)
      elif cmd.startswith("include-code"):
        match = re.search("include-code\s+(?P<name>.*):(?P<path>.*)!\*/", cmd)
        def a(s): self.gen.markdown[-1].append(s)
        a("<div class='panel-group' id='accordion'>")
        a("  <div class='panel panel-default'>")
        a("    <div class='panel-heading'>")
        a("      <h4 class='panel-title'>")
        a("        <a data-toggle='collapse' data-parent='#accordion' href='#clps-1'>")
        a("          " + match.group("name"))
        a("        </a>")
        a("      </h4>")
        a("    </div>")
        a("    <div id='clps-1' class='panel-collapse collapse'>")
        a("      <div class='panel-body'>")
        a("{% capture s %}")
        a("{% include " + match.group("path") + " %}")
        a("{% endcapture %}")
        a("{{ s | markdownify }}")
        a("      </div>")
        a("    </div>")
        a("  </div>")
        a("</div>")
        return self
      elif cmd.startswith("begin-include"):
        self.gen.markdown.append([])
        return self
      elif cmd.startswith("end-include"):
        path = re.search("end-include\((?P<path>.*)\)", cmd).group("path")
        last = self.gen.markdown.pop(-1)
        self.gen.dump(last, os.path.join(self.gen.includes_dir, path))
        return self
      else:
        abort("Unknown command encountered in free mode at {}: {}".format(no, cmd))


class MarkdownMode(object):
  def __init__(self, gen, depth):
    self.gen = gen
    self.depth = depth

  def consume(self, line, no):
    if line.strip().startswith("!*/"):
      self.gen.markdown[-1].append("")
      return FreeMode(self.gen)
    elif line[:self.depth] and not line[:self.depth].isspace():
      abort("Markdown at depth " + str(self.depth) + ", line " + str(no) + ", " +
        "contains improperly indented text:\n" + line)
    else:
      self.gen.markdown[-1].append(line[self.depth:][:-1])
      return self


class CodeMode(object):
  def __init__(self, gen, depth):
    self.gen = gen
    self.depth = depth
    self.started = False

  def consume(self, line, no):
    if not self.started:
      self.gen.markdown[-1].append("```" + self.gen.code_keyword())
      self.started = True

    if line.strip() == "/*!end-code!*/":
      self.gen.markdown[-1].append("```")
      self.gen.markdown[-1].append("")
      return FreeMode(self.gen)
    elif line.strip().startswith("/*!"):
      abort("Line " + no + " starts with command syntax while in code mode: " + line)
    elif line[:self.depth] and not line[:self.depth].isspace():
      abort("Code at depth " + str(self.depth) + ", line " + str(no) + ", " +
        "contains improperly indented text:\n" + line)
    else:
      self.gen.markdown[-1].append(line[self.depth:][:-1])
      return self


class Gen(object):
  def dump(self, lines, path):
    logv("Outputting to " + path + ":\n" + "\n".join(lines))
    with open(path, "w") as f:
      for line in lines:
        f.write(line + "\n")

  def generate(self, path, output_dir, includes_dir):
    self.includes_dir = includes_dir
    if not os.path.exists(includes_dir):
      os.makedirs(includes_dir)

    mode = self.initialMode()
    with open(path, "r") as f:
      no = 0
      for line in f:
        no += 1
        mode = mode.consume(line, no)
    filename, ext = os.path.splitext(os.path.basename(path))
    output_path = os.path.join(output_dir, filename + ".md")

    if not self.markdown[-1]:
      return

    if not os.path.exists(output_dir):
      os.makedirs(output_dir)

    self.dump(self.markdown[-1], output_path)


class ScalaGen(Gen):
  def __init__(self):
    self.markdown = [[]]

  def matches(self, path):
    return path.endswith(".scala")

  def code_keyword(self):
    return "scala"

  def initialMode(self):
    return FreeMode(self)


class JavaGen(Gen):
  def __init__(self):
    self.markdown = [[]]

  def matches(self, path):
    return path.endswith(".java")

  def code_keyword(self):
    return "java"

  def initialMode(self):
    return FreeMode(self)


_generators = {
  "scala": lambda: ScalaGen(),
  "java": lambda: JavaGen()
}


def generatorFor(path):
  return next((gen() for gen in _generators.values() if gen().matches(path)), None)


def main(args):
  parser = argparse.ArgumentParser(
    description="Produces markdown docs from annotated unit tests.")
  parser.add_argument("-p", "--path", required=True,
    help="Path to specific file or file tree to generate documentation for.")
  parser.add_argument("-o", "--output-dir", required=True,
    help="Output directory for the generated documentation files.")
  parser.add_argument("--includes-dir", required=True,
    help="Output directory for the generated include files.")
  parser.add_argument("-v", "--verbose", default=False,
    help="Turn on verbose output.")
  args = parser.parse_args(args[1:])

  global _verbose
  _verbose = args.verbose

  if os.path.isfile(args.path):
    gen = generatorFor(args.path)
    if not gen:
      abort("File {} does not have extension {}.".format(args.path, extension))
    path = os.path.abspath(args.path)
    gen.generate(path, args.output_dir, args.includes_dir)
  else:
    for root, dirs, files in os.walk(args.path):
      for file in files:
        path = os.path.abspath(os.path.join(root, file))
        gen = generatorFor(path)
        if gen:
          relpath = os.path.abspath(root)[len(os.path.abspath(args.path)) + 1:]
          output_path = os.path.join(os.path.abspath(args.output_dir), relpath)
          gen.generate(path, output_path, args.includes_dir)


if __name__ == "__main__":
  main(sys.argv)
