#!/usr/bin/env python

import argparse
import os
import sys

_verbose = False


def log(s):
  print(s)


def loge(s):
  sys.stderr.write(s + "\n")
  sys.stderr.flush()


def logv(s):
  if _verbose:
    log(s)


def abort(s):
  loge(s)
  sys.exit(1)


class FreeMode(object):
  def __init__(self, gen):
    self.gen = gen

  def consume(self, line, no):
    if not line.strip().startswith("/*!"):
      return self
    else:
      cmd = line.strip()[3:]
      depth = line.find("/*!")
      if cmd == "md":
        return MarkdownMode(self.gen, depth)
      elif cmd.startswith("begin-code"):
        return CodeMode(self.gen, depth)
      else:
        abort("Unknown command encountered in free mode at {}: {}".format(no, cmd))


class MarkdownMode(object):
  def __init__(self, gen, depth):
    self.gen = gen
    self.depth = depth

  def consume(self, line, no):
    if line.strip().startswith("!*/"):
      self.gen.markdown.append("")
      return FreeMode(self.gen)
    elif line[:self.depth] and not line[:self.depth].isspace():
      abort("Markdown at depth " + str(self.depth) + ", line " + str(no) + ", " +
        "contains improperly indented text:\n" + line)
    else:
      self.gen.markdown.append(line[self.depth:][:-1])
      return self


class CodeMode(object):
  def __init__(self, gen, depth):
    self.gen = gen
    self.depth = depth
    self.started = False

  def consume(self, line, no):
    if not self.started:
      self.gen.markdown.append("```scala")
      self.started = True

    if line.strip() == "/*!end-code!*/":
      self.gen.markdown.append("```")
      self.gen.markdown.append("")
      return FreeMode(self.gen)
    elif line.strip().startswith("/*!"):
      abort("Line " + no + " starts with command syntax while in code mode: " + line)
    elif line[:self.depth] and not line[:self.depth].isspace():
      abort("Code at depth " + str(self.depth) + ", line " + str(no) + ", " +
        "contains improperly indented text:\n" + line)
    else:
      self.gen.markdown.append(line[self.depth:][:-1])
      return self


class Gen(object):
  def generate(self, path, output_dir):
    mode = self.initialMode()
    with open(path, "r") as f:
      no = 0
      for line in f:
        no += 1
        mode = mode.consume(line, no)
    filename, ext = os.path.splitext(os.path.basename(path))
    output_path = os.path.join(output_dir, filename + ".md")

    if not self.markdown:
      return

    if not os.path.exists(output_dir):
      os.makedirs(output_dir)

    logv("Outputting to " + output_path + ":\n" + "\n".join(self.markdown))
    with open(output_path, "w") as f:
      for line in self.markdown:
        f.write(line + "\n")


class ScalaGen(Gen):
  def __init__(self):
    self.markdown = []

  def matches(self, path):
    return path.endswith(".scala")

  def initialMode(self):
    return FreeMode(self)


class JavaGen(Gen):
  def __init__(self):
    self.markdown = []

  def matches(self, path):
    return path.endswith(".java")

  def initialMode(self):
    return FreeMode(self)


_generators = {
  "scala": lambda: ScalaGen()
  "java": lambda: JavaGen()
}


def generatorFor(path):
  return next((gen() for gen in _generators.values() if gen().matches(path)), None)


def main(args):
  parser = argparse.ArgumentParser(
    description="Produces markdown docs from annotated unit tests.")
  parser.add_argument("-p", "--path", required=True,
    help="Path to specific file or file tree to generate documentation for.")
  parser.add_argument("-o", "--output", required=True,
    help="Output directory for the generated documentation files.")
  parser.add_argument("-v", "--verbose", default=False,
    help="Turn on verbose output.")
  args = parser.parse_args(args[1:])

  global _verbose
  _verbose = args.verbose

  if os.path.isfile(args.path):
    gen = generatorFor(args.path)
    if not gen:
      abort("File {} does not have extension {}.".format(args.path, extension))
    path = os.path.abspath(args.path)
    gen.generate(path, args.output)
  else:
    for root, dirs, files in os.walk(args.path):
      for file in files:
        path = os.path.abspath(os.path.join(root, file))
        gen = generatorFor(path)
        if gen:
          relpath = os.path.abspath(root)[len(os.path.abspath(args.path)) + 1:]
          output_path = os.path.join(os.path.abspath(args.output), relpath)
          gen.generate(path, output_path)


if __name__ == "__main__":
  main(sys.argv)
